# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

parameters:
  - name: Name
    displayName: Script name
    default: test_first.py

trigger:
- master

pool:
  name: TestPool

stages:
  # ----------- Build stage ------------------
  - stage: Build
    displayName: Building stage

    jobs:      
      - job: Build
        displayName: Save repo artifact
        steps:
          - checkout: self
          - script: pip install -r requirements.txt   

          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: '$(Build.SourcesDirectory)'
              artifact: 'repo'
              publishLocation: 'pipeline'

  # ----------- Run tests -------------------
  - stage: Tests
    displayName: Run Python tests
    dependsOn: Build
    condition: succeeded()

    jobs:
      - job: Tests
        displayName: Run Tests
        steps:
        - task: DownloadBuildArtifacts@1
          inputs:
            buildType: 'current'
            downloadType: 'single'
            artifactName: 'repo'
            downloadPath: '$(System.ArtifactsDirectory)'
        - script:  python3 '$(System.ArtifactsDirectory)/${{ parameters.Name }}'
        - task: PublishPipelineArtifact@1
          inputs:
            targetPath: '$(System.DefaultWorkingDirectory)/output'
            artifact: 'test_results'