# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


trigger:
- master

pool:
  name: TestPool

stages:
  - stage: Write
    displayName: Write to file

    jobs:      
      - job: Write
        displayName: Write to file
        steps:
          - script: echo Tralalal >> message.txt  

          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: '$(Build.SourcesDirectory)'
              artifact: 'repo'
              publishLocation: 'pipeline'

  # ----------- Run tests -------------------
  - stage: Read
    displayName: Read content
    dependsOn: Write
    condition: succeeded()

    jobs:
      - job: Read
        displayName: Read content
        steps:
        - task: DownloadBuildArtifacts@1
          inputs:
            buildType: 'current'
            downloadType: 'single'
            artifactName: 'repo'
            downloadPath: '$(System.ArtifactsDirectory)'
        - script: cat '$(System.ArtifactsDirectory)/message.txt'